version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    volumes:
      - ./downloads:/home/seluser/Downloads
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    volumes:
      - ./downloads:/home/seluser/Downloads
  searchPageTest:
    image: automationtesting99/selenium-grid-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - MODULE=SearchPage.xml
      - BROWSER=firefox
    volumes:
      - ./output/searchPageTestsResult:/usr/share/Project3/test-output
  bookflightTest:
    image: automationtesting99/selenium-grid-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - MODULE=Book_Flight.xml
      - BROWSER=chrome
    volumes:
      - ./output/bookFlightTestsResult:/usr/share/Project3/test-output
